In [1]:
import training
import torch

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/Users/max/Documents/JKU/_Master_Thesis/venv/bin/python"
  * The NumPy version is: "1.25.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/max/Documents/JKU/_Master_Thesis/venv/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libcblas.3.dylib
  Referenced from: <B11253D1-0241-35C4-ABCE-3E10495F236F> /Users/max/Documents/JKU/_Master_Thesis/venv/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so
  Reason: tried: '/Users/max/Documents/JKU/_Master_Thesis/venv/lib/python3.11/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/Users/max/Documents/JKU/_Master_Thesis/venv/lib/python3.11/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/Users/max/Documents/JKU/_Master_Thesis/venv/bin/../lib/libcblas.3.dylib' (no such file), '/Users/max/Documents/JKU/_Master_Thesis/venv/bin/../lib/libcblas.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libcblas.3.dylib' (no such file), '/Users/max/Documents/JKU/_Master_Thesis/venv/lib/python3.11/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/Users/max/Documents/JKU/_Master_Thesis/venv/lib/python3.11/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/Users/max/Documents/JKU/_Master_Thesis/venv/bin/../lib/libcblas.3.dylib' (no such file), '/Users/max/Documents/JKU/_Master_Thesis/venv/bin/../lib/libcblas.3.dylib' (no such file), '/usr/local/lib/libcblas.3.dylib' (no such file), '/usr/lib/libcblas.3.dylib' (no such file, not in dyld cache)


In [4]:
# Check that MPS is available
if torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")
device

device(type='mps')

In [5]:
# Data handling
import pandas as pd
import numpy as np

# Bokeh libraries
from bokeh.io import output_file, output_notebook
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource
from bokeh.layouts import row, column, gridplot


# Prepare the data

# Determine where the visualization will be rendered
#output_file('filename.html')  # Render to static HTML, or 
output_notebook()  # Render inline in a Jupyter Notebook

# My x-y coordinate data
x = [1, 2, 1]
y = [1, 1, 2]

# Create a figure with no toolbar and axis ranges of [0,3]
fig = figure(
    title='My Coordinates',
    height=300, width=300,
    x_range=(0, 3), y_range=(0, 3),
    #toolbar_location=None
)

# Draw the coordinates as circles
fig.circle(
    x=x, y=y,
    color='green', 
    size=10, 
    alpha=0.5
)

# Preview and save 
show(fig)  # See what I made, and save if I like it

Loading BokehJS ...

In [31]:
import torch.nn as nn
# 1 1 2 3 5 8 13 21
model = nn.Sequential(
    # nn.Linear(21, 13),
    # nn.ReLU(),
    # nn.Linear(13, 8),
    # nn.ReLU(),
    # nn.Linear(8, 5),
     nn.ReLU(),
    nn.Linear(5, 3)
)
def get_coordinates(model: nn.Sequential):
    layers = len(model)

    for i, module in enumerate(model):
        params = list(module.parameters())

        if len(params) == 2:
            weights, biases = params
            print(f"weights \n {weights.detach().numpy()}")
            print(f"biases \n{biases.detach().numpy()}")

            num_out, num_in = weights.shape
            print(num_in, num_out)



get_coordinates(model)

weights 
 [[-0.11398914 -0.29578435 -0.31762052  0.34640825  0.3589487 ]
 [-0.3390657  -0.22602412  0.287292   -0.34039766  0.40408248]
 [-0.24064724 -0.19828567 -0.00382823 -0.31991175  0.23035681]]
biases 
[0.30145466 0.10608929 0.44383967]
5 3


In [7]:
from bokeh.layouts import column
from bokeh.models import ColumnDataSource, CustomJS, Slider
from bokeh.plotting import figure, show

x = [x*0.005 for x in range(0, 200)]
y = x

source = ColumnDataSource(data=dict(x=x, y=y))

fig = figure(
    width=400, height=400, 
    x_range=(0, 1), y_range=(0, 1)
)

fig.line(
    'x', 'y', 
    source=source, 
    line_width=3, 
    line_alpha=0.6
)

callback = CustomJS(
    args=dict(source=source), 
    code="""
    const f = cb_obj.value
    const x = source.data.x
    const y = Array.from(x, (x) => Math.pow(x, f))
    source.data = { x, y }
    """
)

slider = Slider(start=0.1, end=4, value=1, step=.1, title="power")
slider.js_on_change('value', callback)

layout = column(slider, plot)

show(layout)
